name: build-and-push-auv-images

on:
  push:
    paths:
      - 'Dockerfile.landside'
      - 'Dockerfile.onBoard'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push the landside Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.landside
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref }}:landside

      - name: Build and push the onboard Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.onBoard
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref }}:onboard
          platforms: linux/arm/v8
